"""Generate scripts/main.py — a single runnable Python script equivalent of notebooks/main.ipynb.

Usage:
    python scripts/build_main_script.py

The generated `scripts/main.py` extracts every code cell from main.ipynb,
strips IPython-specific magics, and concatenates them under section banners
that mirror the markdown structure. Useful as Joel's worst-case fallback if
the notebook orchestrator misbehaves on a marker's machine.
"""
from __future__ import annotations
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NB_PATH = ROOT / "notebooks" / "main.ipynb"
OUT_PATH = ROOT / "scripts" / "main.py"


HEADER = '''"""scripts/main.py — single-file equivalent of notebooks/main.ipynb.

Auto-generated by `scripts/build_main_script.py`. Do NOT edit by hand —
edit `scripts/build_main_notebook.py`, run `scripts/build_main_notebook.py`,
then run `scripts/build_main_script.py` to refresh this file.

This script consolidates every helper function from the team's domain
notebooks (1.1 EDA, 1.2 Vocab, 2.1 Baseline, 2.2 RoBERTa, 2.3 LoRA, 4 Error
Analysis, 5 Efficiency) into one place so a marker can read the entire
pipeline top-to-bottom without launching Jupyter.

Usage (local):
    cd <repo-root>
    python scripts/main.py

Usage (Colab):
    !git clone https://github.com/TheFinix13/NLP-coursework.git
    %cd NLP-coursework
    !pip install -q -r requirements.txt
    !python scripts/main.py

Toggle the FROM_SCRATCH / RUN_ERROR_ANALYSIS / RUN_BENCHMARK flags at the
top of the script to control whether heavy training / inference runs.
"""
from __future__ import annotations
import os, sys, subprocess, pathlib

# Make the repo root importable when running from any cwd
PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

# Headless matplotlib — script can run without a display
import matplotlib
matplotlib.use("Agg")
'''


SECTION_MAP = [
    ("0", "Setup", "## 0. Setup"),
    ("1.1", "Distribution and class imbalance (EDA)", "### 1.1 Distribution"),
    ("1.2", "Vocabulary analysis", "### 1.2 Vocabulary"),
    ("2.1", "TF-IDF + LR / SVM baselines", "### 2.1 TF-IDF"),
    ("2.2", "RoBERTa cross-variety", "### 2.2 RoBERTa"),
    ("2.3", "LoRA adapters", "### 2.3 LoRA"),
    ("3", "Cross-task evaluation summary", "## 3. Evaluation"),
    ("4", "Error analysis & few-shot", "## 4. Sarcasm explanation"),
    ("5", "Deployment & efficiency", "## 5. Deployment"),
]


def section_for(md_text: str) -> str | None:
    for tag, _name, prefix in SECTION_MAP:
        if md_text.lstrip().startswith(prefix):
            return tag
    return None


def banner(tag: str, name: str) -> str:
    line = "# " + "=" * 76
    return f"\n\n{line}\n# § {tag} — {name}\n{line}\n"


def strip_magics(src: str) -> str:
    """Remove IPython %-magics that don't run in plain Python."""
    out = []
    for line in src.split("\n"):
        s = line.lstrip()
        if s.startswith("%run "):
            script = s[len("%run "):].strip()
            indent = line[: len(line) - len(s)]
            out.append(f"{indent}subprocess.run([sys.executable, '{script}'], check=True)")
        elif s.startswith("%") or s.startswith("!"):
            out.append("# " + line + "  # (skipped — IPython magic)")
        else:
            out.append(line)
    return "\n".join(out)


def main() -> None:
    nb = json.loads(NB_PATH.read_text())
    pieces: list[str] = [HEADER]
    current_section: str | None = None

    for cell in nb["cells"]:
        if cell["cell_type"] == "markdown":
            md = "".join(cell["source"])
            tag = section_for(md)
            if tag and tag != current_section:
                name = next(n for t, n, _ in SECTION_MAP if t == tag)
                pieces.append(banner(tag, name))
                current_section = tag
            continue

        src = "".join(cell["source"]).rstrip()
        if not src:
            continue
        # Skip the Colab-clone-and-pip block (we tell users to do it manually
        # at the top of main.py docstring); keep the rest of cell 0.5
        if "subprocess.run([\"pip\", \"install\"" in src:
            continue
        pieces.append("\n" + strip_magics(src) + "\n")

    pieces.append("\n\nprint('\\n=== main.py finished ===')\n")

    out = "\n".join(pieces)
    OUT_PATH.write_text(out)
    print(f"Wrote {OUT_PATH} ({len(out):,} chars, {out.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
