# -*- coding: utf-8 -*-
"""LR_Feature_Extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZHKN5LvAylKCg0pO2wMg3wMz3Sq3mwI
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import save_npz
import joblib
import os

def tfidf_features(df_train, df_val, df_test, text_column='clean_text',
                   max_features=5000, save_path="./tfidf"):

    os.makedirs(save_path, exist_ok=True)
    vectorizer = TfidfVectorizer(
        max_features=max_features,
        ngram_range=(1, 2),
        stop_words='english',
        min_df=2,
        max_df=0.95
    )


    X_train_tfidf = vectorizer.fit_transform(df_train[text_column])
    X_val_tfidf = vectorizer.transform(df_val[text_column])
    X_test_tfidf = vectorizer.transform(df_test[text_column])

    # Save vectorizer
    joblib.dump(vectorizer, f"{save_path}/tfidf_vectorizer.pkl")
    # Save TF-IDF matrices
    save_npz(f"{save_path}/X_train_tfidf.npz", X_train_tfidf)
    save_npz(f"{save_path}/X_val_tfidf.npz", X_val_tfidf)
    save_npz(f"{save_path}/X_test_tfidf.npz", X_test_tfidf)

    return X_train_tfidf, X_val_tfidf, X_test_tfidf, vectorizer


def load_tfidf_features(save_path="./tfidf"):
    #load vectorizer
    vectorizer = joblib.load(f"{save_path}/tfidf_vectorizer.pkl")
    
    # Load TF-IDF matrices
    X_train = load_npz(f"{save_path}/X_train_tfidf.npz")
    X_val = load_npz(f"{save_path}/X_val_tfidf.npz")
    X_test = load_npz(f"{save_path}/X_test_tfidf.npz")
    
    return X_train, X_val, X_test, vectorizer
