# -*- coding: utf-8 -*-
"""Logistic Regression Class_Helper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kV7GQpoF96hl9loSYML16hmGhmU9EZ2S

**Logistic Regression Functions & class**

Author: Umme-Yusrah Sumtally

Separate Models for Sentiment and Sarcasm Classification


Citations: Srirag, Dipankar, Aditya Joshi, Jordan Painter, and Diptesh Kanojia. 2025.
BESSTIE: A Benchmark for Sentiment and Sarcasm Classification for Varieties of English.

Imports
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold, cross_val_score
import joblib
import numpy as np

"""**Helper Functions**


*   extract_labels(): Extract true sentiment and sarcasm labels from data
*   calculate_metrics(): calculate all metrics needed for evaluation
*   find_best_threshold(): Threshold tuning on validation set to maximise Macro F1
*   tune C(): C regularisation tuning via stratified cross-validation




"""

def extract_labels(y_df):
    sarcasm_labels = y_df['Sarcasm'].astype(int).values
    sentiment_labels = y_df['Sentiment'].astype(int).values
    return sarcasm_labels, sentiment_labels

def calculate_metrics(y_true, y_pred):
    return {
        'F1_Macro':  f1_score(y_true, y_pred, average='macro', zero_division=0),  #primary metric for this imbalanced dataset
        'Accuracy':  accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred, zero_division=0),  #zero division=0 -- prevents crashes on degenerate predictions
        'Recall':    recall_score(y_true, y_pred, zero_division=0),
        'F1':        f1_score(y_true, y_pred, zero_division=0),
    }

def find_best_threshold(model, X_val, y_val, task_name):
    #Find the decision threshold that maximises Macro F1 on the validation set.

    probabilities = model.predict_proba(X_val)[:, 1]
    best_threshold = 0.5
    best_macro_f1 = 0.0

    for thr in np.arange(0.10, 0.90, 0.01):
        predictions = (probabilities >= thr).astype(int)
        if len(np.unique(predictions)) < 2:
            continue
        macro_f1 = f1_score(y_val, predictions, average='macro', zero_division=0)
        if macro_f1 > best_macro_f1:
            best_macro_f1 = macro_f1
            best_threshold = thr

    return round(best_threshold, 2)

def tune_C(X_train, y_train, task_name):
    #Find the best regularisation strength C
    best_C = 1.0
    best_macro_f1_score = 0.0
    search_candidates = [0.01, 0.1, 0.5, 1.0, 5.0, 10.0]

    for C in search_candidates:
        model = LogisticRegression(
            C=C,
            solver='liblinear',
            class_weight='balanced',
            max_iter=1000,
            random_state=42
        )
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='f1_macro')
        mean_score = scores.mean()

        if mean_score > best_macro_f1_score:
            best_macro_f1_score = mean_score
            best_C = C

    return best_C

"""**Separate Models Class**"""

class SeparateLR:
    """
    Separate optimised Logistic Regression models for sarcasm and sentiment.

    Training pipeline:
      1. Tune regularisation C per task via 5-fold stratified cross-validation.
      2. Train each model on the full training set with best C.
      3. Tune decision threshold per task on the validation set to maximise Macro F1.

    Prediction uses the tuned thresholds (not the default 0.5).
    """

    def __init__(self):
        self.sarcasm_model = None
        self.sentiment_model = None

        self.sarcasm_threshold = 0.5
        self.sentiment_threshold = 0.5

        self.is_trained = False

    # Training 2 separate models[one for each task]
    def train_SeparateLR(self, X_train, y_train_df, X_validation=None, y_validation_df=None):
        """
        Parameters:
            X_train & X_validation: TF-IDF feature matrix for training/validation
            y_train_df & y_validation_df:  DataFrame with 'Sarcasm' and 'Sentiment' columns
        """

        #label extraction using helper function
        sarcasm_labels, sentiment_labels = extract_labels(y_train_df)

        # Tune C per task
        sarcasm_C = tune_C(X_train, sarcasm_labels, 'Sarcasm')
        sentiment_C = tune_C(X_train, sentiment_labels, 'Sentiment')

        # Train each model with best C
        self.sarcasm_model = LogisticRegression(
            C= sarcasm_C,
            solver='liblinear',
            class_weight='balanced',
            max_iter=1000,
            random_state=42
        )
        self.sentiment_model = LogisticRegression(
            C=sentiment_C,
            solver='liblinear',
            class_weight='balanced',
            max_iter=1000,
            random_state=42
        )

        #fitting both models on train data only
        self.sarcasm_model.fit(X_train, sarcasm_labels)
        self.sentiment_model.fit(X_train, sentiment_labels)
        self.is_trained = True  #this becomes true because models are now trained

        # Tune thresholds on validation set
        if X_validation is not None and y_validation_df is not None:
            sarcasm_validation_labels, sentiment_validation_labels = extract_labels(y_validation_df)

            self.sarcasm_threshold = find_best_threshold(
                self.sarcasm_model, X_validation, sarcasm_validation_labels, 'Sarcasm'
            )
            self.sentiment_threshold = find_best_threshold(
                self.sentiment_model, X_validation, sentiment_validation_labels, 'Sentiment'
            )
        else:
            print("\n  No validation data provided — default threshold 0.5 used.")

        return self

    # Prediction
    def label_prediction_SeparateLR(self, X_test):
        if self.is_trained == False:
            raise ValueError("Model not trained yet.")

        sarcasm_probabilities = self.sarcasm_model.predict_proba(X_test)[:, 1]
        sentiment_probabilities = self.sentiment_model.predict_proba(X_test)[:, 1]

        #returns hard labels (0/1)
        return {
            'Sarcasm':   (sarcasm_probabilities >= self.sarcasm_threshold).astype(int),
            'Sentiment': (sentiment_probabilities >= self.sentiment_threshold).astype(int)
        }

    def probability_prediction_SeparateLR(self, X_test):
        if self.is_trained == False:
            raise ValueError("Model not trained yet.")

        # raw probabilities for both tasks.
        return {
            'Sarcasm':   self.sarcasm_model.predict_proba(X_test),
            'Sentiment': self.sentiment_model.predict_proba(X_test)
        }

    # Evaluation
    def SeparateLR_evaluation(self, X_test, y_test_df):
        if self.is_trained = False:
            raise ValueError("Model not trained yet.")

        evaluation_predictions = self.label_prediction_SeparateLR(X_test)
        true_sarcasm_labels, true_sentiment_labels = extract_labels(y_test_df)

        return {
            'Sarcasm':   calculate_metrics(true_sarcasm_labels, evaluation_predictions['Sarcasm']),
            'Sentiment': calculate_metrics(true_sentiment_labels, evaluation_predictions['Sentiment'])
        }

    # Save models and their tuned thresholds
    def save_SeparateLR_models(self, filepath_prefix="./models"):
        joblib.dump(self.sarcasm_model,   f"{filepath_prefix}/separate_sarcasm.pkl")
        joblib.dump(self.sentiment_model, f"{filepath_prefix}/separate_sentiment.pkl")
        joblib.dump(
            {
                'sarcasm_threshold':   self.sarcasm_threshold,
                'sentiment_threshold': self.sentiment_threshold
            },
            f"{filepath_prefix}/separate_thresholds.pkl"
        )
        print(f" Models and thresholds saved")

    #load models and their tuned thresholds
    def load_SeparateLR_models(self, filepath_prefix="./models"):
        self.sarcasm_model   = joblib.load(f"{filepath_prefix}/separate_sarcasm.pkl")
        self.sentiment_model = joblib.load(f"{filepath_prefix}/separate_sentiment.pkl")
        models_thresholds = joblib.load(f"{filepath_prefix}/separate_thresholds.pkl")
        self.sarcasm_threshold   = models_thresholds['sarcasm_threshold']
        self.sentiment_threshold = models_thresholds['sentiment_threshold']
        self.is_trained = True
        print(f"Models and thresholds loaded")
        return self