# -*- coding: utf-8 -*-
"""LogisticRegression_MultiOutput_&_Separate models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFMfgnIsPnejyMbxN1axkmW59UVqM8bL
"""

'''
Desc: Logistic Regression models for Sentiment and Sarcasm classification
      - MultiOutputClassifier (single model for both tasks)
      - Separate models (individual models per task) -- BESSTIE PAPER Approach
'''
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import joblib
import numpy as np



# HELPER FUNCTIONS
def label_extraction(y_df):
    """Extract sarcasm and sentiment labels from dataframe"""
    sarcasm_labels = y_df['Sarcasm'].astype(int).values
    sentiment_labels = y_df['Sentiment'].astype(int).values
    return sarcasm_labels, sentiment_labels


def metrics_computation(y_true, y_pred, task_name):
    """Calculate and return metrics for a single task"""
    return {
        'Accuracy': accuracy_score(y_true, y_pred),
        'F1': f1_score(y_true, y_pred),
        'F1_Macro': f1_score(y_true, y_pred, average='macro'),
        'Precision': precision_score(y_true, y_pred),
        'Recall': recall_score(y_true, y_pred)
    }



# MULTI-OUTPUT MODEL

class MultiOutputLR:
    """
    Multi-output model: Single model predicting both tasks simultaneously
    """
    def __init__(self, lr_parameters=None):
        default_lr = {
            'C': 1.0,
            'solver': 'liblinear',
            'class_weight': 'balanced',
            'max_iter': 1000,
            'random_state': 42
        }
        params = lr_parameters if lr_parameters else default_lr
        self.MultiOutputLR_model = MultiOutputClassifier(LogisticRegression(**params))
        self.is_trained = False

    def train_MultiOutputLR(self, X_train, y_train_df):
        """Train on both sarcasm and sentiment simultaneously"""
        sarcasm_labels, sentiment_labels = label_extraction(y_train_df)
        y_train = np.column_stack([sarcasm_labels, sentiment_labels])
        self.MultiOutputLR_model.fit(X_train, y_train)
        self.is_trained = True
        return self

    def prediction_MultiOutputLR(self, X_test):
        """Predict both tasks"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")
        preds = self.MultiOutputLR_model.predict(X_test)
        return {
            'Sarcasm': preds[:, 0],
            'Sentiment': preds[:, 1]
        }

    def probability_prediction_MultiOutputLR(self, X_test):
        """Get probability predictions"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")
        probs = self.MultiOutputLR_model.predict_proba(X_test)
        return {
            'Sarcasm': probs[0],
            'Sentiment': probs[1]
        }

    def MultiOutputLR_evaluation(self, X_test, y_test_df):
        """Evaluate model on test data"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")

        MultiOutputLR_predictions = self.prediction_MultiOutputLR(X_test)
        true_sarcasm_labels, true_sentiment_labels = label_extraction(y_test_df)

            # DEBUG: Check if labels are different
        print("Sarcasm labels - unique:", np.unique(true_sarcasm_labels), "mean:", np.mean(true_sarcasm_labels))
        print("Sentiment labels - unique:", np.unique(true_sentiment_labels), "mean:", np.mean(true_sentiment_labels))
        
        # DEBUG: Check if predictions are different
        print("Sarcasm predictions - unique:", np.unique(MultiOutputLR_predictions['Sarcasm']), "mean:", np.mean(MultiOutputLR_predictions['Sarcasm']))
        print("Sentiment predictions - unique:", np.unique(MultiOutputLR_predictions['Sentiment']), "mean:", np.mean(MultiOutputLR_predictions['Sentiment']))

        return {
            'Sarcasm': metrics_computation(true_sarcasm_labels, MultiOutputLR_predictions['Sarcasm'], 'Sarcasm'),
            'Sentiment': metrics_computation(true_sentiment_labels, MultiOutputLR_predictions['Sentiment'], 'Sentiment')
        }

    def save_MultiOutputLR_model(self, filepath="./models/multi_output_lr.pkl"):
        joblib.dump(self.MultiOutputLR_model, filepath)
        print(f"✅ Model saved to {filepath}")

    def load_MultiOutputLR_model(self, filepath="./models/multi_output_lr.pkl"):
        self.MultiOutputLR_model = joblib.load(filepath)
        self.is_trained = True
        print(f"✅ Model loaded from {filepath}")
        return self

# SEPARATE MODELS
class SeparateLR:
    """
    Separate models: One model for sarcasm, one for sentiment
    """
    def __init__(self, lr_parameters=None):
        default_lr = {
            'C': 1.0,
            'solver': 'liblinear',
            'class_weight': 'balanced',
            'max_iter': 1000,
            'random_state': 42
        }
        params = lr_parameters if lr_parameters else default_lr
        self.sarcasm_model = LogisticRegression(**params)
        self.sentiment_model = LogisticRegression(**params)
        self.is_trained = False

    def train_SeparateLR(self, X_train, y_train_df):
        """Train separate models for each task"""
        sarcasm_labels, sentiment_labels = label_extraction(y_train_df)

        self.sarcasm_model.fit(X_train, sarcasm_labels)
        self.sentiment_model.fit(X_train, sentiment_labels)
        self.is_trained = True
        return self

    def prediction_SeparateLR(self, X_test):
        """Predict using both models"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")
        return {
            'Sarcasm': self.sarcasm_model.predict(X_test),
            'Sentiment': self.sentiment_model.predict(X_test)
        }

    def probability_prediction_SeparateLR(self, X_test):
        """Get probability predictions"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")
        return {
            'Sarcasm': self.sarcasm_model.predict_proba(X_test),
            'Sentiment': self.sentiment_model.predict_proba(X_test)
        }

    def SeparateLR_evaluation(self, X_test, y_test_df):
        """Evaluate both models on test data"""
        if self.is_trained ==False:
            raise ValueError("Model not trained yet")

        SeparateLR_predictions = self.prediction_SeparateLR(X_test)
        true_sarcasm_labels, true_sentiment_labels = label_extraction(y_test_df)

            # DEBUG: Check if labels are different
        print("Sarcasm labels - unique:", np.unique(true_sarcasm_labels), "mean:", np.mean(true_sarcasm_labels))
        print("Sentiment labels - unique:", np.unique(true_sentiment_labels), "mean:", np.mean(true_sentiment_labels))
        
        # DEBUG: Check if predictions are different
        print("Sarcasm predictions - unique:", np.unique(SeparateLR_predictions['Sarcasm']), "mean:", np.mean(SeparateLR_predictions['Sarcasm']))
        print("Sentiment predictions - unique:", np.unique(SeparateLR_predictions['Sentiment']), "mean:", np.mean(SeparateLR_predictions['Sentiment']))

        return {
            'Sarcasm': metrics_computation(true_sarcasm_labels, SeparateLR_predictions['Sarcasm'], 'Sarcasm'),
            'Sentiment': metrics_computation(true_sentiment_labels, SeparateLR_predictions['Sentiment'], 'Sentiment')
        }

    def save_SeparateLR_models(self, filepath_prefix="./models"):
        """Save both models"""
        joblib.dump(self.sarcasm_model, f"{filepath_prefix}/separate_sarcasm.pkl")
        joblib.dump(self.sentiment_model, f"{filepath_prefix}/separate_sentiment.pkl")
        print(f"✅ Models saved to {filepath_prefix}/")

    def load_SeparateLR_models(self, filepath_prefix="./models"):
        """Load both models"""
        self.sarcasm_model = joblib.load(f"{filepath_prefix}/separate_sarcasm.pkl")
        self.sentiment_model = joblib.load(f"{filepath_prefix}/separate_sentiment.pkl")
        self.is_trained = True
        print(f"✅ Models loaded from {filepath_prefix}/")
        return self
