# -*- coding: utf-8 -*-
"""Logistic_Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZHKN5LvAylKCg0pO2wMg3wMz3Sq3mwI
"""

from sklearn.linear_model import LogisticRegression
import joblib
import os


def train_logistic_regression(X_train, y_train, task_name="sentiment", save_path="./models"):
    os.makedirs(save_path, exist_ok=True)

    LR_model = LogisticRegression(
        C=1.0,
        max_iter=1000,
        class_weight='balanced',
        random_state=42,
        solver='liblinear'
    )

    # Train
    LR_model.fit(X_train, y_train)

    # Save model
    joblib.dump(LR_model, f"{save_path}/logreg_{task_name}.pkl")

    return model


def train_both_models(X_train, y_train_sent, y_train_sarc, save_path="./models"):

    # sentiment model
    Sentiment_model = train_logistic_regression(
        X_train, y_train_sent,
        task_name="Sentiment",
        save_path=save_path
    )

    # sarcasm model
    Sarcasm_model = train_logistic_regression(
        X_train, y_train_sarc,
        task_name="Sarcasm",
        save_path=save_path
    )

    return Sentiment_model, Sarcasm_model