# -*- coding: utf-8 -*-
"""SVM_TFIDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/NLP-sequence-classification
"""

'''
Desc: SVM models for Sentiment and Sarcasm classification
      - MultiOutputSVM  (single model for both tasks)
      - SeparateSVM     (individual models per task) -- BESSTIE PAPER Approach
'''
from sklearn.svm import LinearSVC
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import joblib
import numpy as np



# HELPER FUNCTIONS
def label_extraction(y_df):
    """Extract sarcasm and sentiment labels from dataframe"""
    sarcasm_labels = y_df['Sarcasm'].astype(int).values
    sentiment_labels = y_df['Sentiment'].astype(int).values
    return sarcasm_labels, sentiment_labels


def metrics_computation(y_true, y_pred, task_name):
    """Calculate and return metrics for a single task"""
    return {
        'Accuracy': accuracy_score(y_true, y_pred),
        'F1': f1_score(y_true, y_pred),
        'F1_Macro': f1_score(y_true, y_pred, average='macro'),
        'Precision': precision_score(y_true, y_pred),
        'Recall': recall_score(y_true, y_pred)
    }



# MULTI-OUTPUT MODEL

class MultiOutputSVM:
    """
    Multi-output model: Single SVM predicting both tasks simultaneously
    """
    def __init__(self, svm_parameters=None):
        default_svm = {
            'C': 1.0,
            'class_weight': 'balanced',
            'max_iter': 2000,
            'random_state': 42
        }
        params = svm_parameters if svm_parameters else default_svm
        self.MultiOutputSVM_model = MultiOutputClassifier(LinearSVC(**params))
        self.is_trained = False

    def train_MultiOutputSVM(self, X_train, y_train_df):
        """Train on both sarcasm and sentiment simultaneously"""
        sarcasm_labels, sentiment_labels = label_extraction(y_train_df)
        y_train = np.column_stack([sarcasm_labels, sentiment_labels])
        self.MultiOutputSVM_model.fit(X_train, y_train)
        self.is_trained = True
        return self

    def prediction_MultiOutputSVM(self, X_test):
        """Predict both tasks"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")
        preds = self.MultiOutputSVM_model.predict(X_test)
        return {
            'Sarcasm': preds[:, 0],
            'Sentiment': preds[:, 1]
        }

    def MultiOutputSVM_evaluation(self, X_test, y_test_df):
        """Evaluate model on test data"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")

        MultiOutputSVM_predictions = self.prediction_MultiOutputSVM(X_test)
        true_sarcasm_labels, true_sentiment_labels = label_extraction(y_test_df)

        # DEBUG: Check if labels are different
        print("Sarcasm labels - unique:", np.unique(true_sarcasm_labels), "mean:", np.mean(true_sarcasm_labels))
        print("Sentiment labels - unique:", np.unique(true_sentiment_labels), "mean:", np.mean(true_sentiment_labels))

        # DEBUG: Check if predictions are different
        print("Sarcasm predictions - unique:", np.unique(MultiOutputSVM_predictions['Sarcasm']), "mean:", np.mean(MultiOutputSVM_predictions['Sarcasm']))
        print("Sentiment predictions - unique:", np.unique(MultiOutputSVM_predictions['Sentiment']), "mean:", np.mean(MultiOutputSVM_predictions['Sentiment']))

        return {
            'Sarcasm': metrics_computation(true_sarcasm_labels, MultiOutputSVM_predictions['Sarcasm'], 'Sarcasm'),
            'Sentiment': metrics_computation(true_sentiment_labels, MultiOutputSVM_predictions['Sentiment'], 'Sentiment')
        }

    def save_MultiOutputSVM_model(self, filepath="./models/multi_output_svm.pkl"):
        joblib.dump(self.MultiOutputSVM_model, filepath)
        print(f"✅ Model saved to {filepath}")

    def load_MultiOutputSVM_model(self, filepath="./models/multi_output_svm.pkl"):
        self.MultiOutputSVM_model = joblib.load(filepath)
        self.is_trained = True
        print(f"✅ Model loaded from {filepath}")
        return self


# SEPARATE MODELS
class SeparateSVM:
    """
    Separate models: One SVM for sarcasm, one for sentiment
    """
    def __init__(self, svm_parameters=None):
        default_svm = {
            'C': 1.0,
            'class_weight': 'balanced',
            'max_iter': 2000,
            'random_state': 42
        }
        params = svm_parameters if svm_parameters else default_svm
        self.sarcasm_model = LinearSVC(**params)
        self.sentiment_model = LinearSVC(**params)
        self.is_trained = False

    def train_SeparateSVM(self, X_train, y_train_df):
        """Train separate models for each task"""
        sarcasm_labels, sentiment_labels = label_extraction(y_train_df)

        self.sarcasm_model.fit(X_train, sarcasm_labels)
        self.sentiment_model.fit(X_train, sentiment_labels)
        self.is_trained = True
        return self

    def prediction_SeparateSVM(self, X_test):
        """Predict using both models"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")
        return {
            'Sarcasm': self.sarcasm_model.predict(X_test),
            'Sentiment': self.sentiment_model.predict(X_test)
        }

    def SeparateSVM_evaluation(self, X_test, y_test_df):
        """Evaluate both models on test data"""
        if self.is_trained == False:
            raise ValueError("Model not trained yet")

        SeparateSVM_predictions = self.prediction_SeparateSVM(X_test)
        true_sarcasm_labels, true_sentiment_labels = label_extraction(y_test_df)

        # DEBUG: Check if labels are different
        print("Sarcasm labels - unique:", np.unique(true_sarcasm_labels), "mean:", np.mean(true_sarcasm_labels))
        print("Sentiment labels - unique:", np.unique(true_sentiment_labels), "mean:", np.mean(true_sentiment_labels))

        # DEBUG: Check if predictions are different
        print("Sarcasm predictions - unique:", np.unique(SeparateSVM_predictions['Sarcasm']), "mean:", np.mean(SeparateSVM_predictions['Sarcasm']))
        print("Sentiment predictions - unique:", np.unique(SeparateSVM_predictions['Sentiment']), "mean:", np.mean(SeparateSVM_predictions['Sentiment']))

        return {
            'Sarcasm': metrics_computation(true_sarcasm_labels, SeparateSVM_predictions['Sarcasm'], 'Sarcasm'),
            'Sentiment': metrics_computation(true_sentiment_labels, SeparateSVM_predictions['Sentiment'], 'Sentiment')
        }

    def save_SeparateSVM_models(self, filepath_prefix="./models"):
        """Save both models"""
        joblib.dump(self.sarcasm_model, f"{filepath_prefix}/separate_svm_sarcasm.pkl")
        joblib.dump(self.sentiment_model, f"{filepath_prefix}/separate_svm_sentiment.pkl")
        print(f"✅ Models saved to {filepath_prefix}/")

    def load_SeparateSVM_models(self, filepath_prefix="./models"):
        """Load both models"""
        self.sarcasm_model = joblib.load(f"{filepath_prefix}/separate_svm_sarcasm.pkl")
        self.sentiment_model = joblib.load(f"{filepath_prefix}/separate_svm_sentiment.pkl")
        self.is_trained = True
        print(f"✅ Models loaded from {filepath_prefix}/")
        return self
